"""受控大类词表【种子/真源】(设计 docs/design/ingest-category-standard.md)。

三份数据,一处维护(代码即真源,git 可审可回滚;Neon 的 categories/category_aliases
两表由 perception/setup_categories.py 从这里同步,供 SQL join 用):
  · CATEGORIES            —— 受控大类(~26 个,英文小写;它们会以 predicate 行写进 video_facts)
  · ALIASES               —— 别名/同义词/中文 → 大类(查询桥:「跳伞」「做饭」都能对上)
  · PREDICATE_TO_CATEGORY —— 现有 197 个细谓词 → 大类(回填映射表;人工已审)

规则:一个谓词只属于一个大类;video 级主类由 taxonomy.main_categories_for 依多数决
(泛化类靠后)推导,恰 1 个、并列最多 2 个。
"""
from __future__ import annotations

# ── 受控大类(video_facts 里的大类行就用这些字符串)─────────────────────
CATEGORIES: list[str] = [
    "skydiving", "winter sports", "water sports", "climbing", "skateboarding",
    "cycling", "motorsports", "ball sports", "martial arts & wrestling", "fitness",
    "paintball & shooting", "equestrian", "music", "dancing", "cooking & food",
    "holiday & party", "personal care", "household & cleaning", "diy & crafts",
    "car care", "shopping", "talking & presenting", "beach & leisure", "spectating",
    "celebration & awards", "everyday activities",
]

# 泛化类:多数决时【靠后】(有具体活动类就别用它当主类)
GENERIC_CATEGORIES = {"everyday activities", "talking & presenting", "spectating"}

# ── 别名 → 大类(查询桥用;全部小写比对)────────────────────────────────
ALIASES: dict[str, str] = {
    # skydiving
    "跳伞": "skydiving", "翼装": "skydiving", "翼装飞行": "skydiving",
    "wingsuit": "skydiving", "parachute": "skydiving", "高空跳伞": "skydiving",
    # winter sports
    "滑雪": "winter sports", "单板滑雪": "winter sports", "双板滑雪": "winter sports",
    "冰壶": "winter sports", "冬季运动": "winter sports",
    "skiing": "winter sports", "snowboarding": "winter sports", "curling": "winter sports",
    # water sports
    "潜水": "water sports", "游泳": "water sports", "帆板": "water sports",
    "风帆冲浪": "water sports", "水上运动": "water sports",
    "scuba": "water sports", "scuba diving": "water sports",
    "swimming": "water sports", "windsurfing": "water sports", "diving": "water sports",
    # climbing
    "攀岩": "climbing", "攀爬": "climbing", "rock climbing": "climbing",
    # skateboarding
    "滑板": "skateboarding", "skate": "skateboarding", "skateboard": "skateboarding",
    # cycling
    "骑车": "cycling", "自行车": "cycling", "骑行": "cycling",
    "bike": "cycling", "bicycle": "cycling",
    # motorsports
    "摩托": "motorsports", "摩托车": "motorsports", "越野摩托": "motorsports",
    "赛车": "motorsports", "motocross": "motorsports", "motorcycle": "motorsports",
    # ball sports
    "球类": "ball sports", "排球": "ball sports", "躲避球": "ball sports",
    "飞盘": "ball sports", "打球": "ball sports",
    "volleyball": "ball sports", "dodgeball": "ball sports", "frisbee": "ball sports",
    # martial arts & wrestling
    "武术": "martial arts & wrestling", "相扑": "martial arts & wrestling",
    "摔跤": "martial arts & wrestling", "掰手腕": "martial arts & wrestling",
    "sumo": "martial arts & wrestling", "martial arts": "martial arts & wrestling",
    "arm wrestling": "martial arts & wrestling",
    # fitness
    "健身": "fitness", "锻炼": "fitness", "跑步": "fitness",
    "exercise": "fitness", "workout": "fitness", "running": "fitness",
    # paintball & shooting
    "彩弹": "paintball & shooting", "真人cs": "paintball & shooting",
    "射击": "paintball & shooting", "paintball": "paintball & shooting",
    "shooting": "paintball & shooting",
    # equestrian
    "骑马": "equestrian", "马术": "equestrian", "horse riding": "equestrian",
    "riding horse": "equestrian",
    # music
    "音乐": "music", "乐器": "music", "唱歌": "music", "吉他": "music",
    "架子鼓": "music", "小提琴": "music",
    "guitar": "music", "drums": "music", "violin": "music", "singing": "music",
    # dancing
    "跳舞": "dancing", "舞蹈": "dancing", "dance": "dancing",
    # cooking & food
    "做饭": "cooking & food", "烹饪": "cooking & food", "做菜": "cooking & food",
    "吃饭": "cooking & food", "美食": "cooking & food", "沙拉": "cooking & food",
    "cooking": "cooking & food", "food": "cooking & food", "salad": "cooking & food",
    # holiday & party
    "节日": "holiday & party", "圣诞": "holiday & party", "圣诞节": "holiday & party",
    "万圣节": "holiday & party", "派对": "holiday & party", "南瓜": "holiday & party",
    "christmas": "holiday & party", "halloween": "holiday & party", "party": "holiday & party",
    # personal care
    "美发": "personal care", "洗手": "personal care", "护理": "personal care",
    "美容": "personal care", "hair": "personal care", "hygiene": "personal care",
    # household & cleaning
    "家务": "household & cleaning", "清洁": "household & cleaning",
    "吸尘": "household & cleaning", "打扫": "household & cleaning",
    "cleaning": "household & cleaning", "vacuum": "household & cleaning",
    "vacuuming": "household & cleaning",
    # diy & crafts
    "手工": "diy & crafts", "diy": "diy & crafts", "家具": "diy & crafts",
    "上釉": "diy & crafts", "crafts": "diy & crafts", "furniture": "diy & crafts",
    # car care
    "洗车": "car care", "汽车": "car care", "car": "car care", "car wash": "car care",
    # shopping
    "购物": "shopping", "逛街": "shopping", "store": "shopping",
    # talking & presenting
    "演讲": "talking & presenting", "讲解": "talking & presenting",
    "说话": "talking & presenting", "采访": "talking & presenting",
    "presentation": "talking & presenting", "speech": "talking & presenting",
    # beach & leisure
    "海滩": "beach & leisure", "沙滩": "beach & leisure", "无人机": "beach & leisure",
    "beach": "beach & leisure", "drone": "beach & leisure",
    # spectating
    "观赛": "spectating", "观看": "spectating", "观众": "spectating",
    "watching": "spectating", "spectator": "spectating",
    # celebration & awards
    "庆祝": "celebration & awards", "颁奖": "celebration & awards",
    "领奖": "celebration & awards", "celebration": "celebration & awards",
    "award": "celebration & awards",
    # everyday activities
    "日常": "everyday activities", "生活": "everyday activities",
    "daily": "everyday activities", "everyday": "everyday activities",
}

# ── 197 个既有细谓词 → 大类(回填映射;每谓词恰一类)──────────────────────
PREDICATE_TO_CATEGORY: dict[str, str] = {
    "adjusting hairdryer settings": "personal care",
    "admiring christmas tree": "holiday & party",
    "applying cream to arm": "personal care",
    "applying glaze with a brush": "diy & crafts",
    "applying hair roller": "personal care",
    "applying soap": "personal care",
    "applying vertical hair roller": "personal care",
    "arm wrestling": "martial arts & wrestling",
    "assembling christmas tree": "holiday & party",
    "assembling vacuum cleaner": "household & cleaning",
    "attaching hairdryer nozzle": "personal care",
    "browsing greeting cards": "shopping",
    "carrying chair": "diy & crafts",
    "catching ball": "ball sports",
    "celebrating": "celebration & awards",
    "celebrating victory": "celebration & awards",
    "cheering": "spectating",
    "cleaning chair": "household & cleaning",
    "clipping quickdraws": "climbing",
    "collecting candy": "holiday & party",
    "combing hair": "personal care",
    "communicating": "talking & presenting",
    "comparing tires": "car care",
    "congratulating": "celebration & awards",
    "crawling": "everyday activities",
    "curling": "winter sports",
    "cutting pumpkin": "holiday & party",
    "cycling (stationary bike)": "fitness",
    "dancing": "dancing",
    "decorating christmas tree with lights": "holiday & party",
    "decorating christmas tree with ornaments": "holiday & party",
    "delivering curling stone": "winter sports",
    "demonstrating glazing technique": "diy & crafts",
    "demonstrating putting on shoes": "everyday activities",
    "demonstrating removing shoes": "everyday activities",
    "demonstrating sumo stance": "martial arts & wrestling",
    "disassembling vacuum cleaner": "household & cleaning",
    "diving": "water sports",
    "dodging ball": "ball sports",
    "doing lunges": "fitness",
    "doing push-ups": "fitness",
    "drawing on pumpkin": "holiday & party",
    "drinking": "cooking & food",
    "drinking beer": "cooking & food",
    "drinking eggnog": "holiday & party",
    "driving car": "car care",
    "drying car": "car care",
    "drying hair with discomfort": "personal care",
    "drying hair with satisfaction": "personal care",
    "drying hands": "personal care",
    "eating": "cooking & food",
    "eating salad": "cooking & food",
    "examining arm": "personal care",
    "exercising": "fitness",
    "explaining": "talking & presenting",
    "explaining hair styling techniques": "personal care",
    "falling": "everyday activities",
    "filming": "everyday activities",
    "gesturing while speaking": "talking & presenting",
    "getting eliminated (paintball)": "paintball & shooting",
    "getting hit by ball": "ball sports",
    "getting out of car": "car care",
    "group exercise": "fitness",
    "hand washing car": "car care",
    "handling merchandise": "shopping",
    "hanging clothes": "household & cleaning",
    "hitting piñata": "holiday & party",
    "holding car wheel": "car care",
    "honing knife": "cooking & food",
    "huddling": "ball sports",
    "inspecting damaged hair": "personal care",
    "instructing sumo techniques": "martial arts & wrestling",
    "interacting with dog": "everyday activities",
    "kicking frisbee": "ball sports",
    "kneeling": "everyday activities",
    "looking at camera": "everyday activities",
    "looking at watch": "everyday activities",
    "making fake snow": "holiday & party",
    "manualing across a ledge": "skateboarding",
    "motocross racing": "motorsports",
    "ollieing into a manual": "skateboarding",
    "ollieing up a curb": "skateboarding",
    "operating drone": "beach & leisure",
    "operating machinery": "diy & crafts",
    "operating vacuum cleaner switch": "household & cleaning",
    "painting chair": "diy & crafts",
    "painting vehicle parts": "car care",
    "passing or setting volleyball": "ball sports",
    "people clapping": "spectating",
    "performing a manual": "skateboarding",
    "performing a nose manual": "skateboarding",
    "performing manual flip tricks": "skateboarding",
    "performing martial arts": "martial arts & wrestling",
    "performing sumo drill": "martial arts & wrestling",
    "picking up chair": "diy & crafts",
    "placing items on chair": "diy & crafts",
    "playing beach volleyball": "ball sports",
    "playing beer pong": "holiday & party",
    "playing dodgeball": "ball sports",
    "playing drums": "music",
    "playing guitar": "music",
    "playing paintball": "paintball & shooting",
    "playing records": "music",
    "playing sports": "ball sports",
    "playing violin": "music",
    "playing volleyball": "ball sports",
    "playing with fake snow": "holiday & party",
    "playing with pumpkin guts": "holiday & party",
    "playing with sandcastle": "beach & leisure",
    "pointing at car wheel": "car care",
    "pointing at car wheel well": "car care",
    "politicians speaking": "talking & presenting",
    "posing for photo": "everyday activities",
    "posing with styled hair": "personal care",
    "preparing salad": "cooking & food",
    "presenting information": "talking & presenting",
    "putting on helmet": "everyday activities",
    "reapplying glaze": "diy & crafts",
    "receiving award": "celebration & awards",
    "refereeing arm wrestling": "martial arts & wrestling",
    "removing carved pieces": "holiday & party",
    "removing shoes": "everyday activities",
    "riding bicycle": "cycling",
    "riding horse": "equestrian",
    "riding motorcycle": "motorsports",
    "rinsing hands": "personal care",
    "rock climbing": "climbing",
    "running": "fitness",
    "sanding chair": "diy & crafts",
    "scooping pumpkin guts": "holiday & party",
    "scoring goal": "ball sports",
    "scuba diving": "water sports",
    "securing hair roller with pin": "personal care",
    "serving volleyball": "ball sports",
    "sharpening knife": "cooking & food",
    "shooting": "paintball & shooting",
    "shooting (paintball marker)": "paintball & shooting",
    "showing collected debris": "household & cleaning",
    "showing product": "shopping",
    "showing tools": "diy & crafts",
    "singing": "music",
    "sitting": "everyday activities",
    "skateboarding": "skateboarding",
    "skiing": "winter sports",
    "skydiving": "skydiving",
    "smiling": "everyday activities",
    "snowboarding": "winter sports",
    "speaking to camera": "talking & presenting",
    "spectating": "spectating",
    "spiking volleyball": "ball sports",
    "squatting": "fitness",
    "standing on beach": "beach & leisure",
    "standing up": "everyday activities",
    "step aerobics": "fitness",
    "sumo wrestling": "martial arts & wrestling",
    "sumo wrestling preparation": "martial arts & wrestling",
    "sweeping curling stone": "winter sports",
    "swimming": "water sports",
    "taking cover": "paintball & shooting",
    "talking": "talking & presenting",
    "talking to camera": "talking & presenting",
    "talking to the camera": "talking & presenting",
    "teaching": "talking & presenting",
    "throwing ball": "ball sports",
    "throwing frisbee": "ball sports",
    "transitioning to kneeling": "everyday activities",
    "turning off water": "personal care",
    "turning on water": "personal care",
    "vacuuming car interior": "car care",
    "vacuuming carpet": "household & cleaning",
    "vacuuming ceiling": "household & cleaning",
    "vacuuming floor": "household & cleaning",
    "vacuuming furniture": "household & cleaning",
    "vacuuming hard floor": "household & cleaning",
    "waiting in a store": "shopping",
    "walking": "everyday activities",
    "walking on beach": "beach & leisure",
    "washing car": "car care",
    "washing car with pressure washer": "car care",
    "washing clothes": "household & cleaning",
    "washing hands": "personal care",
    "watching game": "spectating",
    "watching something": "spectating",
    "watching sport": "spectating",
    "watching sports": "spectating",
    "wearing backpack vacuum cleaner": "household & cleaning",
    "wetting and wringing a cloth": "household & cleaning",
    "wetting hands": "personal care",
    "windsurfer falling": "water sports",
    "windsurfer jumping": "water sports",
    "windsurfer preparing to launch": "water sports",
    "windsurfing": "water sports",
    "wingsuit skydiving": "skydiving",
    "wiping chair": "household & cleaning",
    "wiping glaze off a surface": "diy & crafts",
    "wiping mouth": "cooking & food",
    "working on roof": "diy & crafts",
}
