"""GD-2b:评测专用假世界 C(城市生活/职业)—— 与世界 A/B 实体互斥,金标可跨世界翻转。

由 evals/task_gen.py 消费;MOCK_WORLD=C 时 repl._mock_db 载入本文件。
种子即真相:出题金标全部从这里推导,改种子必须重跑生成器 + split_tool。
"""

# (video_id, title, gcs_uri, duration_seconds, [activities])
VIDEOS_C = [
    ('c001', 'First Driving Lesson Downtown', 'gs://activitynet/c001.mp4', 62, ['driving lesson', 'parallel parking']),
    ('c002', 'Rush Hour Subway Commute', 'gs://activitynet/c002.mp4', 48, ['subway commute', 'riding train']),
    ('c003', 'Classic Barbershop Fade', 'gs://activitynet/c003.mp4', 55, ['barbershop haircut', 'trimming hair']),
    ('c004', 'Saturday Farmers Market Stroll', 'gs://activitynet/c004.mp4', 75, ['farmers market', 'shopping produce']),
    ('c005', 'Quarterly Office Presentation', 'gs://activitynet/c005.mp4', 88, ['office presentation', 'public speaking']),
    ('c006', 'Fixing a Flat Bicycle Tire', 'gs://activitynet/c006.mp4', 44, ['bicycle repair', 'changing tire']),
    ('c007', 'Firefighter Ladder Drill', 'gs://activitynet/c007.mp4', 68, ['firefighter drill', 'ladder exercise']),
    ('c008', 'Wood-Fired Pizza Making', 'gs://activitynet/c008.mp4', 58, ['pizza making', 'tossing dough']),
    ('c009', 'Violin Busker at the Plaza', 'gs://activitynet/c009.mp4', 51, ['violin performance', 'busking']),
    ('c010', 'Parkour Across Rooftop Gaps', 'gs://activitynet/c010.mp4', 39, ['parkour', 'vaulting']),
    ('c011', 'Hand Car Wash Detailing', 'gs://activitynet/c011.mp4', 47, ['car washing', 'detailing']),
    ('c012', 'High-Rise Window Cleaning', 'gs://activitynet/c012.mp4', 73, ['window cleaning', 'rope access']),
    ('c013', 'Tailor Hemming Suit Trousers', 'gs://activitynet/c013.mp4', 64, ['tailoring', 'sewing']),
    ('c014', 'Hand Bookbinding Workshop', 'gs://activitynet/c014.mp4', 92, ['bookbinding', 'stitching pages']),
    ('c015', 'Courier Package Delivery Run', 'gs://activitynet/c015.mp4', 36, ['package delivery', 'scanning parcels']),
    ('c016', 'Street Magician Card Tricks', 'gs://activitynet/c016.mp4', 42, ['street magic', 'card tricks']),
    ('c017', 'Morning Tai Chi in the Plaza', 'gs://activitynet/c017.mp4', 78, ['tai chi', 'group exercise']),
    ('c018', 'Metro Escalator Crowd Timelapse', 'gs://activitynet/c018.mp4', 21, ['escalator crowd', 'timelapse']),
    ('c019', 'Taco Food Truck Lunch Rush', 'gs://activitynet/c019.mp4', 59, ['food truck service', 'cooking tacos']),
    ('c020', 'Shoe Shine at Central Station', 'gs://activitynet/c020.mp4', 27, ['shoe shining', 'polishing shoes']),
]

# (video_id, predicate, matched, confidence, rationale, start_s, end_s)
FACTS_C = [
    ('c001', 'driving lesson', 1, 0.95, 'Instructor guiding student driver through city streets', 2, 58),
    ('c001', 'parallel parking', 1, 0.87, 'Student parallel parks between two cars', 40, 52),
    ('c001', 'checking mirrors', 1, 0.72, 'Student adjusts and checks mirrors before pulling out', 3, 8),
    ('c002', 'subway commute', 1, 0.94, 'Commuters boarding a crowded subway train', 0, 48),
    ('c002', 'swiping fare card', 1, 0.83, 'Passenger taps fare card at the turnstile', 4, 7),
    ('c002', 'train arriving', 1, 0.9, 'Train pulls into the platform and doors open', 10, 16),
    ('c003', 'barbershop haircut', 1, 0.96, 'Barber cutting a fade in a barbershop chair', 2, 52),
    ('c003', 'using clippers', 1, 0.91, 'Clippers shaping the sides of the head', 8, 30),
    ('c003', 'applying shaving cream', 0, 0.25, 'Haircut only, no shave or cream in this clip', 0, 0),
    ('c004', 'farmers market', 1, 0.95, 'Stalls of fresh produce with shoppers browsing', 0, 75),
    ('c004', 'weighing produce', 1, 0.84, 'Vendor weighs tomatoes on a hanging scale', 25, 32),
    ('c004', 'paying in cash', 1, 0.76, 'Shopper hands cash to the stall vendor', 33, 37),
    ('c005', 'office presentation', 1, 0.94, 'Presenter walking through slides in a meeting room', 2, 85),
    ('c005', 'pointing at slides', 1, 0.86, 'Presenter points at a figure on the projector screen', 30, 44),
    ('c005', 'audience applause', 1, 0.68, 'Colleagues applaud at the end of the talk', 82, 86),
    ('c006', 'bicycle repair', 1, 0.95, 'Mechanic repairing a bicycle on a work stand', 0, 44),
    ('c006', 'patching inner tube', 1, 0.88, 'Inner tube patched after locating the puncture', 15, 28),
    ('c006', 'pumping tire', 1, 0.81, 'Tire inflated with a floor pump', 34, 40),
    ('c007', 'firefighter drill', 1, 0.95, 'Firefighters running a timed training drill', 0, 68),
    ('c007', 'extending ladder', 1, 0.89, 'Truck ladder extended toward the training tower', 12, 25),
    ('c007', 'spraying water hose', 1, 0.85, 'Crew sprays the hose at a practice target', 40, 60),
    ('c008', 'pizza making', 1, 0.96, 'Cook preparing a pizza from dough to slice', 0, 58),
    ('c008', 'tossing dough', 1, 0.9, 'Dough spun and tossed in the air', 6, 14),
    ('c008', 'spreading tomato sauce', 1, 0.87, 'Sauce ladled and spread over the base', 18, 24),
    ('c009', 'violin performance', 1, 0.96, 'Street musician bowing a violin for passersby', 2, 48),
    ('c009', 'tips in open case', 1, 0.8, 'Open violin case collecting coins and bills', 0, 51),
    ('c009', 'crowd gathering', 1, 0.74, 'Small crowd stops to listen to the busker', 20, 40),
    ('c010', 'parkour', 1, 0.95, 'Athlete flowing over urban obstacles between rooftops', 0, 39),
    ('c010', 'vaulting over railing', 1, 0.88, 'Clean vault over a metal railing', 9, 13),
    ('c010', 'wall run', 1, 0.84, 'Athlete takes three steps up a concrete wall', 22, 27),
    ('c011', 'car washing', 1, 0.95, 'Sedan washed by hand with foam and mitts', 0, 47),
    ('c011', 'rinsing with hose', 1, 0.86, 'Foam rinsed off with a pressure hose', 25, 33),
    ('c011', 'drying with towel', 1, 0.79, 'Panels dried with microfiber towels', 36, 45),
    ('c012', 'window cleaning', 1, 0.94, 'Cleaner wiping high-rise windows from outside', 4, 70),
    ('c012', 'suspended rope platform', 1, 0.9, 'Worker suspended on a rope descent platform', 0, 73),
    ('c012', 'using squeegee', 1, 0.88, 'Squeegee strokes clearing soapy glass', 10, 60),
    ('c013', 'tailoring', 1, 0.94, 'Tailor fitting and hemming suit trousers', 0, 64),
    ('c013', 'sewing machine stitching', 1, 0.91, 'Hem stitched on a sewing machine', 30, 47),
    ('c013', 'measuring with tape', 1, 0.85, 'Inseam measured with a tailor tape', 5, 12),
    ('c014', 'bookbinding', 1, 0.95, 'Craftsman binding a hardcover book by hand', 0, 92),
    ('c014', 'stitching signatures', 1, 0.89, 'Folded signatures sewn along the spine', 20, 50),
    ('c014', 'gluing spine', 1, 0.83, 'Glue brushed onto the book spine', 58, 70),
    ('c015', 'package delivery', 1, 0.95, 'Courier delivering parcels door to door', 0, 36),
    ('c015', 'scanning barcode', 1, 0.88, 'Parcel barcode scanned with a handheld device', 8, 11),
    ('c015', 'ringing doorbell', 1, 0.77, 'Courier rings the doorbell and leaves the parcel', 20, 24),
    ('c016', 'street magic', 1, 0.94, 'Magician performing close-up tricks for pedestrians', 0, 42),
    ('c016', 'shuffling cards', 1, 0.9, 'Deck shuffled and fanned for a spectator', 5, 12),
    ('c016', 'coin trick', 0, 0.3, 'Only card tricks shown, no coin routine', 0, 0),
    ('c017', 'tai chi', 1, 0.96, 'Group practicing slow tai chi forms in a plaza', 2, 76),
    ('c017', 'synchronized movements', 1, 0.87, 'Dozens of practitioners moving in unison', 10, 70),
    ('c017', 'sword form', 0, 0.28, 'Bare-hand form only, no sword routine performed', 0, 0),
    ('c018', 'escalator crowd', 1, 0.93, 'Timelapse of commuters streaming up escalators', 0, 21),
    ('c018', 'rush hour crowd', 1, 0.89, 'Dense commuter crowd during evening rush', 0, 21),
    ('c018', 'person tripping', 0, 0.22, 'No one trips on the escalator in this timelapse', 0, 0),
    ('c019', 'food truck service', 1, 0.95, 'Staff serving customers from a taco truck window', 0, 59),
    ('c019', 'cooking on griddle', 1, 0.88, 'Taco filling sizzling on the truck griddle', 10, 35),
    ('c019', 'handing food to customer', 1, 0.82, 'Order handed through the service window', 40, 46),
    ('c020', 'shoe shining', 1, 0.94, 'Shiner buffing leather shoes at a station stand', 0, 27),
    ('c020', 'applying polish', 1, 0.9, 'Polish worked into the leather with a cloth', 4, 14),
    ('c020', 'buffing with brush', 1, 0.85, 'Brush buffing the shoes to a mirror shine', 15, 24),
]
