"""GD-2b:评测专用假世界 D(自然/科学)—— 与世界 A/B 实体互斥,金标可跨世界翻转。

由 evals/task_gen.py 消费;MOCK_WORLD=D 时 repl._mock_db 载入本文件。
种子即真相:出题金标全部从这里推导,改种子必须重跑生成器 + split_tool。
"""

# (video_id, title, gcs_uri, duration_seconds, [activities])
VIDEOS_D = [
    ('d001', 'Horse Riding Lesson at the Ranch', 'gs://activitynet/d001.mp4', 62, ['horse riding', 'trotting']),
    ('d002', 'Birdwatching in the Wetlands', 'gs://activitynet/d002.mp4', 48.5, ['birdwatching', 'using binoculars']),
    ('d003', 'Feeding Tropical Aquarium Fish', 'gs://activitynet/d003.mp4', 25, ['feeding aquarium fish', 'tank cleaning']),
    ('d004', 'Beekeeping Hive Inspection', 'gs://activitynet/d004.mp4', 71, ['beekeeping', 'hive inspection']),
    ('d005', 'Kite Flying on a Windy Hill', 'gs://activitynet/d005.mp4', 33.5, ['kite flying', 'launching kite']),
    ('d006', 'Camping Bonfire Evening', 'gs://activitynet/d006.mp4', 55, ['camping bonfire', 'roasting marshmallows']),
    ('d007', 'Lake Fishing at Dawn', 'gs://activitynet/d007.mp4', 92, ['lake fishing', 'casting line']),
    ('d008', 'Backyard Telescope Stargazing', 'gs://activitynet/d008.mp4', 42, ['telescope stargazing', 'adjusting telescope']),
    ('d009', 'Color Change Chemistry Experiment', 'gs://activitynet/d009.mp4', 37.5, ['chemistry experiment', 'pouring reagents']),
    ('d010', 'Planting the Spring Vegetable Garden', 'gs://activitynet/d010.mp4', 66, ['planting vegetables', 'watering seedlings']),
    ('d011', 'Wood Carving a Small Owl', 'gs://activitynet/d011.mp4', 58.5, ['wood carving', 'whittling']),
    ('d012', 'Archery Target Practice', 'gs://activitynet/d012.mp4', 45, ['archery', 'shooting arrows']),
    ('d013', 'Sheep Herding on the Hillside', 'gs://activitynet/d013.mp4', 52, ['sheep herding', 'whistling commands']),
    ('d014', 'Tomato Greenhouse Tour', 'gs://activitynet/d014.mp4', 39, ['greenhouse tour', 'watering plants']),
    ('d015', 'Butterfly Garden Visit', 'gs://activitynet/d015.mp4', 28.5, ['observing butterflies', 'photographing butterflies']),
    ('d016', 'Folding an Origami Crane', 'gs://activitynet/d016.mp4', 19, ['origami folding', 'creasing paper']),
    ('d017', 'Classroom Robot Demo', 'gs://activitynet/d017.mp4', 34, ['robot demonstration', 'line following']),
    ('d018', 'Waterfall Trail Hike', 'gs://activitynet/d018.mp4', 76.5, ['waterfall hiking', 'stream crossing']),
    ('d019', 'Pumpkin Patch Harvest', 'gs://activitynet/d019.mp4', 49.5, ['harvesting pumpkins', 'loading wagon']),
    ('d020', 'Rowing Boat Across the Lake', 'gs://activitynet/d020.mp4', 63, ['rowing boat', 'pulling oars']),
]

# (video_id, predicate, matched, confidence, rationale, start_s, end_s)
FACTS_D = [
    ('d001', 'horse riding', 1, 0.95, 'A rider guides the horse around the paddock for most of the lesson', 14, 58),
    ('d001', 'brushing the horse', 1, 0.72, "The rider brushes the horse's coat before mounting", 0, 10),
    ('d001', 'trotting', 1, 0.86, 'The horse keeps a steady trot through the middle drills', 24, 41),
    ('d002', 'birdwatching', 1, 0.94, 'A group scans the wetland for birds during the entire clip', 0, 48),
    ('d002', 'using binoculars', 1, 0.88, 'Binoculars are raised repeatedly to follow a heron', 5, 30),
    ('d002', 'taking field notes', 1, 0.61, 'One observer jots sightings into a small notebook', 32, 44),
    ('d003', 'feeding fish', 1, 0.93, 'Flake food is sprinkled on the water and the fish rise to eat', 2, 14),
    ('d003', 'cleaning the tank glass', 1, 0.7, 'A magnetic scrubber wipes algae off the front glass', 15, 23),
    ('d003', 'colorful fish visible', 1, 0.9, 'Bright tropical fish are on screen throughout', 0, 25),
    ('d004', 'beekeeping', 1, 0.96, 'A keeper in a veil works the hive for the full video', 0, 71),
    ('d004', 'inspecting hive frames', 1, 0.89, 'Frames are lifted out one by one to check the brood and honey stores', 12, 52),
    ('d004', 'using a smoker', 1, 0.77, 'Smoke is puffed at the hive entrance to calm the bees', 3, 10),
    ('d005', 'kite flying', 1, 0.94, 'A large kite stays aloft over the hill after launch', 6, 33),
    ('d005', 'launching the kite', 1, 0.82, 'Two people release the kite into the wind at the start', 0, 6),
    ('d005', 'kite crashing', 0, 0.22, 'The kite remains airborne and never hits the ground', 0, 0),
    ('d006', 'camping bonfire', 1, 0.95, 'A bonfire burns at the center of the campsite for the whole clip', 0, 55),
    ('d006', 'roasting marshmallows', 1, 0.85, 'Campers hold marshmallow sticks over the flames', 18, 39),
    ('d006', 'adding firewood', 1, 0.68, 'A camper stacks fresh logs onto the fire early on', 5, 11),
    ('d007', 'lake fishing', 1, 0.96, 'An angler fishes from the bank for the whole video', 0, 92),
    ('d007', 'casting the line', 1, 0.87, 'Several long casts are made toward open water', 4, 20),
    ('d007', 'reeling in a fish', 1, 0.79, 'A small perch is reeled in and lifted from the lake', 61, 74),
    ('d008', 'stargazing', 1, 0.92, 'People take turns looking through the telescope at the night sky', 8, 42),
    ('d008', 'adjusting the telescope', 1, 0.8, 'The mount is aligned and focused before viewing begins', 0, 8),
    ('d008', 'seeing the moon', 0, 0.25, 'The telescope stays aimed at star fields and the moon never appears', 0, 0),
    ('d009', 'chemistry experiment', 1, 0.95, 'A bench experiment runs from setup to the final reaction', 0, 37),
    ('d009', 'pouring reagents', 1, 0.86, 'Two clear solutions are poured into a beaker', 9, 17),
    ('d009', 'color change reaction', 1, 0.9, 'The liquid shifts from clear to deep blue', 24, 31),
    ('d010', 'planting vegetables', 1, 0.94, 'Seedlings are set into prepared rows of soil', 12, 52),
    ('d010', 'digging holes', 1, 0.78, 'Holes are dug along the bed before planting', 0, 12),
    ('d010', 'watering seedlings', 1, 0.83, 'A watering can soaks each new seedling at the end', 53, 65),
    ('d011', 'wood carving', 1, 0.96, 'A carver shapes a small owl figure from a wooden block', 0, 58),
    ('d011', 'whittling with a knife', 1, 0.85, 'Fine knife strokes shave curls off the wood', 10, 40),
    ('d011', 'sanding the figure', 1, 0.7, 'The finished owl is smoothed with sandpaper', 44, 57),
    ('d012', 'archery', 1, 0.95, 'Target practice with a recurve bow fills the clip', 0, 45),
    ('d012', 'drawing the bow', 1, 0.88, 'The archer repeatedly draws and anchors before each release', 5, 35),
    ('d012', 'hitting the bullseye', 1, 0.74, 'One arrow lands in the center ring at the 29 second mark', 28, 31),
    ('d013', 'sheep herding', 1, 0.93, 'A shepherd moves the flock across the hillside', 0, 52),
    ('d013', 'whistling commands', 1, 0.76, 'Sharp whistles direct the flock toward the gate', 8, 30),
    ('d013', 'shearing sheep', 0, 0.2, 'The flock is only moved between pastures and no shearing occurs', 0, 0),
    ('d014', 'greenhouse tour', 1, 0.92, 'A guide leads visitors along rows of tomato plants', 0, 39),
    ('d014', 'watering plants', 1, 0.71, 'An irrigation wand mists the plant beds mid tour', 22, 30),
    ('d014', 'explaining plant care', 1, 0.8, 'The guide describes pruning and feeding routines', 5, 20),
    ('d015', 'observing butterflies', 1, 0.93, 'Visitors watch butterflies moving between flower beds', 0, 28),
    ('d015', 'photographing butterflies', 1, 0.81, 'A visitor snaps close-up photos of a monarch', 10, 22),
    ('d015', 'butterfly landing on hand', 1, 0.65, 'A butterfly briefly rests on an outstretched palm', 23, 26),
    ('d016', 'origami folding', 1, 0.95, 'Hands fold a square sheet into a crane step by step', 0, 19),
    ('d016', 'creasing paper', 1, 0.84, 'Each fold is pressed flat with a fingernail', 2, 12),
    ('d016', 'finished paper crane', 1, 0.72, 'The completed crane is displayed at the end', 16, 19),
    ('d017', 'robot demonstration', 1, 0.94, 'A small wheeled robot is demonstrated to a classroom', 0, 34),
    ('d017', 'robot following a line', 1, 0.86, 'The robot tracks a taped line across the floor', 12, 24),
    ('d017', 'typing code on a laptop', 1, 0.63, 'A presenter tweaks the control script before the run', 4, 11),
    ('d018', 'hiking', 1, 0.95, 'Hikers follow a forest trail up to the waterfall', 0, 76),
    ('d018', 'waterfall view', 1, 0.9, 'The falls come into full view near the end', 58, 76),
    ('d018', 'crossing a stream', 1, 0.73, 'The group steps across rocks in a shallow stream', 30, 38),
    ('d019', 'harvesting pumpkins', 1, 0.94, 'Workers pick ripe pumpkins across the patch', 0, 49),
    ('d019', 'loading a wagon', 1, 0.77, 'Pumpkins are stacked onto a wooden wagon', 28, 45),
    ('d019', 'carving pumpkins', 0, 0.28, 'Pumpkins are picked and hauled whole and none are cut', 0, 0),
    ('d020', 'rowing a boat', 1, 0.95, 'Two rowers pull oars in rhythm across the lake', 4, 60),
    ('d020', 'pulling oars', 1, 0.87, 'Steady oar strokes propel the boat forward', 10, 50),
    ('d020', 'boarding the boat', 1, 0.69, 'The rowers step in and push off from the pier', 0, 4),
]
